### ISSUE TITLE
How to make the data display is in 2 decimal places

### ISSUE THREAD

**Issue by faralawi** [SabraTech/Pedometer#1]
![whatsapp image 2018-04-30 at 9 03 23 pm](https://user-images.githubusercontent.com/26515145/39428485-1b462538-4cba-11e8-8ab8-d37076f5befb.jpeg)

**Comment by SabraTech** [comment]
In the calculateData() method the update of the speed and calories can be rounded before set the text in the TextView in line [229](https://github.com/SabraTech/Pedometer/blob/eeae5862692c3a0cde7183ce0e0406e8b122ee86/Pedometer/app/src/main/java/com/example/sabra/pedometer/Accelerometer.java#L229) and line [232](https://github.com/SabraTech/Pedometer/blob/eeae5862692c3a0cde7183ce0e0406e8b122ee86/Pedometer/app/src/main/java/com/example/sabra/pedometer/Accelerometer.java#L232) you can use this code to round and format the value to be 2 decimal places.

`double value;`
`DecimalFormat df = new DecimalFormat("#.##");`      
`value = Double.valueOf(df.format(value));`
`TextView.setText(value);`

**Comment by faralawi** [comment]
Thank you but where I should use the code? I put the code in calculateData() method but i got an error cannot resolve method 'setText(java.lang.Double)'.

**Comment by SabraTech** [comment]
The setText takes String so you need to the double to string first for example in calculate the speed it will be like this:

`runningSpeed = meters / (((System.currentTimeMillis() - startWatch) * 1000));`
`DecimalFormat df = new DecimalFormat("#.##");`
`runningSpeed = Double.valueOf(df.format(runningSpeed));`
`speed.setText(Double.toString(runningSpeed));`

this code will replace the lines [228](https://github.com/SabraTech/Pedometer/blob/eeae5862692c3a0cde7183ce0e0406e8b122ee86/Pedometer/app/src/main/java/com/example/sabra/pedometer/Accelerometer.java#L228) & [229](https://github.com/SabraTech/Pedometer/blob/eeae5862692c3a0cde7183ce0e0406e8b122ee86/Pedometer/app/src/main/java/com/example/sabra/pedometer/Accelerometer.java#L229)

**Comment by faralawi** [comment]
Ok I got it, thank you so much for helping.
